/**
 * The demo CMS's plugins: the everyday WordPress plugins a clinic site relies
 * on, rebuilt as modules. Each has default settings; the admin renders a
 * settings page from `fields`, and some add their own screens.
 */

export type FieldType = "text" | "textarea" | "toggle" | "number" | "select" | "list" | "password";
export type Field = { key: string; label: string; type: FieldType; help?: string; options?: { value: string; label: string }[]; placeholder?: string; dir?: "ltr" };

export type PluginDef = {
  id: string;
  name: string;
  /** the WordPress plugin people know it from */
  like: string;
  description: string;
  icon: string;
  version: string;
  category: "أساسية" | "المحتوى" | "التسويق" | "الحماية" | "الأداء" | "التكامل";
  /** installed and active in a fresh demo */
  installed: boolean;
  active: boolean;
  settings: Record<string, unknown>;
  fields: Field[];
  /** where its own screen lives in the admin, when it has one */
  screen?: string;
  /** a short note on what it changes on the live site in this demo */
  onSite?: string;
};

export const PLUGINS: PluginDef[] = [
  {
    id: "seo",
    name: "تحسين محركات البحث",
    like: "Yoast SEO",
    description: "عنوان ووصف لكل صفحة مع معاينة نتيجة Google، وتحليل للكلمة المفتاحية، وخريطة الموقع وبيانات المنشأة الطبية.",
    icon: "search",
    version: "3.2.0",
    category: "أساسية",
    installed: true,
    active: true,
    settings: { separator: "|", sitemap: true, schema: true, noindexThankYou: true, ogImage: "/og.jpg" },
    fields: [
      { key: "separator", label: "فاصل العنوان", type: "select", options: [{ value: "|", label: "|" }, { value: "–", label: "–" }, { value: "·", label: "·" }] },
      { key: "sitemap", label: "خريطة الموقع sitemap.xml", type: "toggle", help: "تُحدَّث تلقائيًا مع كل صفحة أو برنامج جديد." },
      { key: "schema", label: "بيانات المنشأة الطبية (MedicalClinic)", type: "toggle", help: "العنوان والهاتف وساعات العمل لنتائج Google والخرائط." },
      { key: "noindexThankYou", label: "إخفاء صفحة الشكر عن محركات البحث", type: "toggle" },
      { key: "ogImage", label: "صورة المشاركة الافتراضية", type: "text", dir: "ltr" },
    ],
    screen: "/seo",
    onSite: "العناوين التي تكتبها هنا تظهر في تبويب المتصفح.",
  },
  {
    id: "forms",
    name: "نماذج الحجز",
    like: "WPForms",
    description: "نموذج الحجز متعدد الخطوات: الحقول الاختيارية، ورسالة التأكيد، وأين تذهب الطلبات.",
    icon: "clipboard-list",
    version: "2.4.1",
    category: "أساسية",
    installed: true,
    active: true,
    settings: { askForWhom: true, askTherapist: true, askPayment: true, destination: "لوحة التحكم + Google Sheets", fallbackWhatsApp: true },
    fields: [
      { key: "askForWhom", label: "سؤال «لمن الحجز؟»", type: "toggle" },
      { key: "askTherapist", label: "تفضيل أخصائي أو أخصائية", type: "toggle" },
      { key: "askPayment", label: "طريقة الدفع والتأمين", type: "toggle" },
      { key: "fallbackWhatsApp", label: "بديل واتساب إن تعذّر الإرسال", type: "toggle" },
      { key: "destination", label: "وجهة الطلبات", type: "select", options: [{ value: "لوحة التحكم + Google Sheets", label: "لوحة التحكم + Google Sheets" }, { value: "لوحة التحكم فقط", label: "لوحة التحكم فقط" }, { value: "CRM عبر Webhook", label: "CRM عبر Webhook" }] },
    ],
    screen: "/leads",
    onSite: "الطلبات من الموقع في هذا المتصفح تصل إلى «الحجوزات» فورًا.",
  },
  {
    id: "appointments",
    name: "المواعيد والتقويم",
    like: "Amelia",
    description: "تقويم أسبوعي للمواعيد المؤكدة، وتوزيعها على الأخصائيين، ومدة الجلسة.",
    icon: "calendar-check",
    version: "1.9.3",
    category: "أساسية",
    installed: true,
    active: true,
    settings: { slotMinutes: 45, therapists: ["أخصائي العظام والعمود الفقري", "أخصائية صحة المرأة", "أخصائي التأهيل الرياضي", "فريق الزيارات المنزلية"], reminders: true },
    fields: [
      { key: "slotMinutes", label: "مدة الموعد (دقيقة)", type: "number" },
      { key: "therapists", label: "الأخصائيون في التقويم", type: "list", help: "سطر لكل أخصائي. ضع الأسماء الحقيقية عند اعتمادها." },
      { key: "reminders", label: "تذكير قبل الموعد بيوم", type: "toggle" },
    ],
    screen: "/leads?view=calendar",
  },
  {
    id: "whatsapp",
    name: "زر واتساب",
    like: "Click to Chat",
    description: "الزر العائم ورسالته الجاهزة وجهة ظهوره.",
    icon: "message-circle",
    version: "4.0.2",
    category: "التسويق",
    installed: true,
    active: true,
    settings: { side: "end", message: "السلام عليكم، أريد الاستفسار عن جلسات العلاج الطبيعي." },
    fields: [
      {
        key: "side",
        label: "مكان الزر",
        type: "select",
        options: [
          { value: "end", label: "يسار الشاشة" },
          { value: "start", label: "يمين الشاشة" },
        ],
      },
      { key: "message", label: "الرسالة الجاهزة", type: "textarea" },
    ],
    onSite: "إيقافها يُخفي الزر العائم، وتغيير الرسالة يظهر عند الضغط عليه.",
  },
  {
    id: "analytics",
    name: "التحليلات والبكسلات",
    like: "Site Kit + PixelYourSite",
    description: "Google Analytics 4 وبكسلات Meta وSnapchat وTikTok وتحويلات Google Ads، مع إرسال الطلبات من الخادم.",
    icon: "chart-line",
    version: "2.1.0",
    category: "التسويق",
    installed: true,
    active: true,
    settings: { ga4Id: "", metaPixelId: "", snapPixelId: "", tiktokPixelId: "", googleAdsId: "", serverEvents: true },
    fields: [
      { key: "ga4Id", label: "معرّف GA4", type: "text", placeholder: "G-XXXXXXXXXX", dir: "ltr" },
      { key: "metaPixelId", label: "بكسل Meta", type: "text", dir: "ltr" },
      { key: "snapPixelId", label: "بكسل Snapchat", type: "text", dir: "ltr" },
      { key: "tiktokPixelId", label: "بكسل TikTok", type: "text", dir: "ltr" },
      { key: "googleAdsId", label: "Google Ads", type: "text", placeholder: "AW-XXXXXXXXX", dir: "ltr" },
      { key: "serverEvents", label: "إرسال الطلبات من الخادم (Conversions API)", type: "toggle", help: "لا تُرسل أي بيانات صحية للمنصات الإعلانية." },
    ],
    screen: "/analytics",
    onSite: "في العرض تُحفظ المعرّفات فقط ولا تُشغَّل البكسلات.",
  },
  {
    id: "security",
    name: "الأمان والجدار الناري",
    like: "Wordfence",
    description: "جدار حماية، وحد لمحاولات الدخول، وتحقق بخطوتين، وفحص للملفات.",
    icon: "shield-check",
    version: "7.11.0",
    category: "الحماية",
    installed: true,
    active: true,
    settings: { firewall: true, loginLimit: 5, lockoutMinutes: 30, twoFactor: true, hideLogin: false },
    fields: [
      { key: "firewall", label: "جدار الحماية", type: "toggle" },
      { key: "loginLimit", label: "محاولات الدخول قبل الحظر", type: "number" },
      { key: "lockoutMinutes", label: "مدة الحظر (دقيقة)", type: "number" },
      { key: "twoFactor", label: "التحقق بخطوتين للمديرين", type: "toggle" },
      { key: "hideLogin", label: "إخفاء رابط الدخول الافتراضي", type: "toggle" },
    ],
    screen: "/security",
  },
  {
    id: "backups",
    name: "النسخ الاحتياطي",
    like: "UpdraftPlus",
    description: "نسخة كاملة من المحتوى والإعدادات، يدوية أو مجدولة، مع استعادة بضغطة.",
    icon: "archive",
    version: "1.24.4",
    category: "الحماية",
    installed: true,
    active: true,
    settings: { schedule: "daily", keep: 7, destination: "Google Drive" },
    fields: [
      { key: "schedule", label: "الجدولة", type: "select", options: [{ value: "daily", label: "يوميًا" }, { value: "weekly", label: "أسبوعيًا" }, { value: "manual", label: "يدويًا فقط" }] },
      { key: "keep", label: "عدد النسخ المحفوظة", type: "number" },
      { key: "destination", label: "مكان الحفظ", type: "select", options: [{ value: "Google Drive", label: "Google Drive" }, { value: "Dropbox", label: "Dropbox" }, { value: "Amazon S3", label: "Amazon S3" }] },
    ],
    screen: "/backups",
  },
  {
    id: "cache",
    name: "الأداء والتخزين المؤقت",
    like: "WP Rocket",
    description: "صفحات جاهزة مسبقًا، وتحميل كسول للصور، وتصغير الملفات، وقياس سرعة الموقع.",
    icon: "gauge",
    version: "3.16.1",
    category: "الأداء",
    installed: true,
    active: true,
    settings: { prerender: true, lazyImages: true, minify: true, preloadFonts: true },
    fields: [
      { key: "prerender", label: "توليد الصفحات مسبقًا", type: "toggle", help: "كل صفحة تصل جاهزة، فتظهر أسرع لزوار الإعلانات." },
      { key: "lazyImages", label: "تحميل الصور عند الحاجة", type: "toggle" },
      { key: "minify", label: "تصغير CSS وJavaScript", type: "toggle" },
      { key: "preloadFonts", label: "تحميل الخط العربي مبكرًا", type: "toggle" },
    ],
    screen: "/performance",
  },
  {
    id: "images",
    name: "ضغط الصور",
    like: "Smush",
    description: "يحوّل الصور المرفوعة إلى WebP ويصغّر مقاساتها، ويعرض ما وفّره.",
    icon: "image",
    version: "3.16.6",
    category: "الأداء",
    installed: true,
    active: true,
    settings: { autoOnUpload: true, maxWidth: 1600, quality: 80 },
    fields: [
      { key: "autoOnUpload", label: "الضغط تلقائيًا عند الرفع", type: "toggle" },
      { key: "maxWidth", label: "أقصى عرض للصورة (px)", type: "number" },
      { key: "quality", label: "الجودة (%)", type: "number" },
    ],
    screen: "/media",
  },
  {
    id: "redirects",
    name: "التحويلات وصفحات 404",
    like: "Redirection",
    description: "تحويل روابط الموقع القديم إلى الصفحات الجديدة حتى لا تضيع زياراتها وترتيبها في Google.",
    icon: "shuffle",
    version: "5.5.0",
    category: "أساسية",
    installed: true,
    active: true,
    settings: { log404: true },
    fields: [{ key: "log404", label: "تسجيل الروابط المكسورة", type: "toggle" }],
    screen: "/redirects",
    onSite: "التحويلات الجديدة تعمل في هذا المتصفح؛ تحويلات الموقع القديم مفعّلة على الخادم.",
  },
  {
    id: "popups",
    name: "النوافذ والعروض",
    like: "Popup Maker",
    description: "نافذة العرض الحالي بعد ثوانٍ من دخول الزائر، مرة واحدة في الزيارة.",
    icon: "gift",
    version: "1.19.0",
    category: "التسويق",
    installed: true,
    active: false,
    settings: { delay: 6, title: "تقييمك الأول مجاني", text: "نفحصك بعناية، وتخرج بخطة علاج مكتوبة. العرض لفترة محدودة.", button: "احجز تقييمك المجاني" },
    fields: [
      { key: "delay", label: "تظهر بعد (ثانية)", type: "number" },
      { key: "title", label: "العنوان", type: "text" },
      { key: "text", label: "النص", type: "textarea" },
      { key: "button", label: "نص الزر", type: "text" },
    ],
    onSite: "فعّلها ثم افتح الموقع: تظهر النافذة بعد الثواني المحددة.",
  },
  {
    id: "reviews",
    name: "آراء المراجعين",
    like: "Site Reviews + Trustindex",
    description: "استقبال الآراء ومراجعتها قبل نشرها، وعرض تقييم Google.",
    icon: "star",
    version: "7.0.4",
    category: "المحتوى",
    installed: true,
    active: false,
    settings: { showOnHome: true, requireConsent: true },
    fields: [
      { key: "showOnHome", label: "عرض الآراء المعتمدة في الرئيسية", type: "toggle" },
      { key: "requireConsent", label: "لا يُنشر رأي دون موافقة موثقة من صاحبه", type: "toggle" },
    ],
    screen: "/reviews",
    onSite: "تنبيه نظامي: قد تقيّد أنظمة الإعلان الصحي نشر شهادات المرضى، فالقسم معطّل افتراضيًا.",
  },
  {
    id: "cookies",
    name: "الخصوصية وملفات الارتباط",
    like: "Complianz",
    description: "شريط موافقة يوقف البكسلات الإعلانية حتى يوافق الزائر، وفق نظام حماية البيانات الشخصية.",
    icon: "cookie",
    version: "7.1.0",
    category: "الحماية",
    installed: true,
    active: false,
    settings: {
      text: "نستخدم ملفات ارتباط لتحسين تجربتك وقياس الإعلانات. لا نشارك أي معلومات صحية.",
      accept: "موافق",
      decline: "الضرورية فقط",
    },
    fields: [
      { key: "text", label: "نص الشريط", type: "textarea" },
      { key: "accept", label: "زر الموافقة", type: "text" },
      { key: "decline", label: "زر الرفض", type: "text" },
    ],
    onSite: "فعّلها ليظهر الشريط أسفل الموقع.",
  },
  {
    id: "maintenance",
    name: "وضع الصيانة",
    like: "SeedProd",
    description: "صفحة «نعود قريبًا» للزوار أثناء التحديثات، ولوحة التحكم تبقى تعمل.",
    icon: "wrench",
    version: "6.17.2",
    category: "أساسية",
    installed: true,
    active: false,
    settings: { title: "نحدّث موقعنا", text: "نعود خلال وقت قصير. للحجز والاستفسار راسلنا على واتساب." },
    fields: [
      { key: "title", label: "العنوان", type: "text" },
      { key: "text", label: "النص", type: "textarea" },
    ],
    onSite: "فعّلها ثم افتح الموقع لترى صفحة الصيانة.",
  },
  {
    id: "multilingual",
    name: "تعدد اللغات",
    like: "WPML",
    description: "نسخة إنجليزية لكل صفحة ومبدّل لغة في الترويسة.",
    icon: "languages",
    version: "4.6.9",
    category: "المحتوى",
    installed: true,
    active: false,
    settings: { english: false, switcher: true },
    fields: [
      { key: "english", label: "تفعيل الإنجليزية", type: "toggle", help: "النصوص الإنجليزية لم تُكتب بعد (0 من 33 صفحة)." },
      { key: "switcher", label: "مبدّل اللغة في الترويسة", type: "toggle" },
    ],
  },
  {
    id: "smtp",
    name: "البريد والتنبيهات",
    like: "WP Mail SMTP",
    description: "من يُبلَّغ بكل حجز جديد، وعبر أي قناة.",
    icon: "bell",
    version: "4.1.1",
    category: "التكامل",
    installed: true,
    active: true,
    settings: { email: "info@healife-ksa.com", whatsapp: "", provider: "Google Workspace", daily: true },
    fields: [
      { key: "email", label: "بريد التنبيه", type: "text", dir: "ltr" },
      { key: "whatsapp", label: "واتساب الاستقبال للتنبيه", type: "text", dir: "ltr", placeholder: "9665XXXXXXXX" },
      { key: "provider", label: "مزوّد البريد", type: "select", options: [{ value: "Google Workspace", label: "Google Workspace" }, { value: "Microsoft 365", label: "Microsoft 365" }, { value: "Zoho Mail", label: "Zoho Mail" }] },
      { key: "daily", label: "ملخص يومي للطلبات", type: "toggle" },
    ],
  },
  {
    id: "antispam",
    name: "مكافحة الرسائل المزعجة",
    like: "Akismet",
    description: "حقل مخفي للروبوتات، وحد أدنى لوقت ملء النموذج، ومجلد للطلبات المشبوهة.",
    icon: "shield-alert",
    version: "5.3.3",
    category: "الحماية",
    installed: true,
    active: true,
    settings: { honeypot: true, minSeconds: 3 },
    fields: [
      { key: "honeypot", label: "حقل مخفي للروبوتات", type: "toggle" },
      { key: "minSeconds", label: "أقل وقت لملء النموذج (ثانية)", type: "number" },
    ],
    screen: "/leads?folder=spam",
  },
  {
    id: "activity",
    name: "سجل النشاط",
    like: "WP Activity Log",
    description: "من غيّر ماذا ومتى في لوحة التحكم.",
    icon: "history",
    version: "5.1.0",
    category: "الحماية",
    installed: true,
    active: true,
    settings: { keepDays: 90 },
    fields: [{ key: "keepDays", label: "مدة الاحتفاظ (يوم)", type: "number" }],
    screen: "/activity",
  },
  // ---- Available to install (the "Add new" catalog) ----
  {
    id: "sheets",
    name: "الطلبات إلى Google Sheets",
    like: "Uncanny Automator",
    description: "كل طلب حجز يُضاف صفًا في جدول Google يراه الاستقبال على الجوال.",
    icon: "table",
    version: "1.2.0",
    category: "التكامل",
    installed: false,
    active: false,
    settings: { sheetUrl: "" },
    fields: [{ key: "sheetUrl", label: "رابط Apps Script (Webhook)", type: "text", dir: "ltr", help: "هذا هو LEAD_WEBHOOK_URL في إعدادات الخادم." }],
  },
  {
    id: "installments",
    name: "التقسيط: تابي وتمارا",
    like: "Tabby / Tamara",
    description: "إظهار «قسّمها على 4 دفعات» على الباقات، وقبول الدفع المقسّط.",
    icon: "credit-card",
    version: "2.0.0",
    category: "التكامل",
    installed: false,
    active: false,
    settings: { tabby: true, tamara: true },
    fields: [
      { key: "tabby", label: "تابي", type: "toggle" },
      { key: "tamara", label: "تمارا", type: "toggle" },
    ],
  },
  {
    id: "payments",
    name: "الدفع الإلكتروني",
    like: "Moyasar",
    description: "دفع العربون أو الباقة بمدى وApple Pay والبطاقات.",
    icon: "wallet",
    version: "1.4.2",
    category: "التكامل",
    installed: false,
    active: false,
    settings: { mada: true, applePay: true, deposit: 0 },
    fields: [
      { key: "mada", label: "مدى", type: "toggle" },
      { key: "applePay", label: "Apple Pay", type: "toggle" },
      { key: "deposit", label: "عربون الحجز (ريال)", type: "number" },
    ],
  },
  {
    id: "sms",
    name: "تذكير المواعيد بالرسائل",
    like: "Unifonic",
    description: "رسالة SMS تؤكد الموعد، وتذكير قبله بيوم، ورابط لإعادة الجدولة.",
    icon: "message-square",
    version: "1.1.0",
    category: "التكامل",
    installed: false,
    active: false,
    settings: { sender: "TajAlasehaa", remindHours: 24 },
    fields: [
      { key: "sender", label: "اسم المرسل", type: "text", dir: "ltr" },
      { key: "remindHours", label: "التذكير قبل (ساعة)", type: "number" },
    ],
  },
  {
    id: "gcal",
    name: "مزامنة تقويم Google",
    like: "Google Calendar",
    description: "المواعيد المؤكدة تظهر في تقويم كل أخصائي.",
    icon: "calendar",
    version: "1.0.4",
    category: "التكامل",
    installed: false,
    active: false,
    settings: { calendar: "" },
    fields: [{ key: "calendar", label: "معرّف التقويم", type: "text", dir: "ltr" }],
  },
  {
    id: "greviews",
    name: "تقييمات Google",
    like: "Trustindex",
    description: "عرض تقييم المركز في خرائط Google ورابط «قيّمنا» بعد الجلسة.",
    icon: "badge-check",
    version: "12.1",
    category: "التسويق",
    installed: false,
    active: false,
    settings: { placeId: "ChIJ00E183GVvRUR0BmyT7Ls7O8" },
    fields: [{ key: "placeId", label: "معرّف المكان في خرائط Google", type: "text", dir: "ltr" }],
  },
  {
    id: "crm",
    name: "ربط نظام العملاء",
    like: "Zoho CRM / HubSpot",
    description: "إرسال كل طلب إلى نظام إدارة العملاء مع مصدره وحملته.",
    icon: "users",
    version: "2.3.1",
    category: "التكامل",
    installed: false,
    active: false,
    settings: { provider: "Zoho CRM", apiKey: "" },
    fields: [
      { key: "provider", label: "النظام", type: "select", options: [{ value: "Zoho CRM", label: "Zoho CRM" }, { value: "HubSpot", label: "HubSpot" }, { value: "Salesforce", label: "Salesforce" }] },
      { key: "apiKey", label: "مفتاح الربط", type: "password", dir: "ltr" },
    ],
  },
];

export const pluginById = (id: string) => PLUGINS.find((p) => p.id === id);
